
name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3


    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.KOHAIISART_SSH_KEY }}
      

    - name: Deploy via rsync
      run: |
        rsync -avz \
          -e "ssh -o StrictHostKeyChecking=no -p 22" \
          ./ root@kohaiiarts.com:/srv/kohaiis.art

    - name: Run post-deploy commands
      run: |
        ssh -o StrictHostKeyChecking=no -p 22 root@kohaiiarts.com << 'EOF'
          export COMPOSER_ALLOW_SUPERUSER=1
          cd /srv/kohaiis.art
          # Ensure the database directory exists
          mkdir -p database
          # Create the SQLite database file if it doesn't exist
          [ -f database/database.sqlite ] || touch database/database.sqlite
          composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
          php artisan migrate --force
          php artisan optimize
          npm ci
          npm run build
          sudo chown -R www-data:www-data /srv/kohaiis.art
        EOF
