name: Deploy to Server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Deploy via rsync
      run: |
        rsync -avz --delete \
          -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.DEPLOY_PORT || '22' }}" \
          ./ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/srv/kohaiis.art

    - name: Run post-deploy commands
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.DEPLOY_PORT || '22' }} ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
          sudo chown -R www-data:www-data /srv/kohaiis.art
          cd /srv/kohaiis.art
          php artisan migrate --force
          php artisan optimize
        EOF